springdoc:
  api-docs:
    path: /openapi/supplementary-service
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v3.0.0
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /bus/v3/api-docs

  cache:
    disabled: true
  packages-to-scan: com.nanum