server:
  port: 0
#logging:
#  level:
#    org.springframework: DEBUG

spring:
  application:
    name: supplementary-service
  profiles:
    include: mysql, swagger, s3
  messages:
    basename: messages

  jpa:
    open-in-view: false

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 3.37.166.100
#spring.cloud.client.hostname
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.37.166.100:8761/eureka
#      defaultZone: http://127.0.0.1:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, info, metrics, prometheus

logging:
  level:
    com.nanum.supplementaryservice.client: DEBUG

